### ISSUE TITLE
odd number tutorial error

### ISSUE THREAD

**Issue by RedBeansAndRice** [erp12/pyshgp#106] opened 2019-03-08 05:23 UTC
I tried to run the odd number tutorial and got an error message reading[ __init__ missing 1 required positional argument: "spawner"], not sure why this is happening

**Comment by erp12** [comment] 2019-03-08 23:03
Thanks for catching this! It looks like the examples weren't updated to reflect the API changes between v0.1.1 and v0.1.2. The examples on `master` should now be compatible with the code on `master`. 

Spawner used to have a default value, but it no longer does. A spawner is used to determine what instructions and literals to use when generating programs, including how many "input instructions". The default assumed no input instructions, which is silly because is is rare to want to synthesize a program with that takes no inputs.

This highlights a need to run all examples before releases. I opened up another issue (#110) specifically for building a script that will do this in order to validate each new release.

**Comment by erp12** [comment] 2019-03-16 02:55
@RedBeansAndRice Have you gotten a chance to to try the examples as they are on master after this fix? I want to make sure that this is actually fixed before closing.

**Comment by erp12** [comment] 2019-03-20 18:13
Closing because the issue is fixed as far as I can tell.

**Closed as completed by erp12** 2019-03-20 18:13 UTC

**Comment by RedBeansAndRice** [comment] 2019-03-21 05:49
Sorry for the late reply. Everything seems to be running smooth. Thanks!!

**Comment by erp12** [comment] 2019-03-24 01:19
@RedBeansAndRice Awesome, glad to hear it! Feel free to open more issues if you encounter anything else.
